apiVersion: v1
kind: Service
metadata:
  name: appweb
  labels:
    apps: appweb
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    nodePort: 30036
    protocol: TCP
  selector:
    app: appweb