apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    appdb: rsvpdb
  name: rsvp-db
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      appdb: rsvpdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        appdb: rsvpdb
    spec:
      containers:
      - env:
        - name: MONGODB_DATABASE
          value: rsvpdata
        image: mongo:3.3
        imagePullPolicy: IfNotPresent
        name: rsvpd-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
